name: mycode
version: 0.1
author: Henrik Andersson

ghc-options: -Wall

dependencies:
  - base >=4.12 && <5

default-extensions:
  - OverloadedStrings

executables:
  ch01:
    source-dirs: ch01
    main: ch01.hs
    other-modules: []
    dependencies:
      - text >=1.2 && <1.3
      - fmt >=0.5 && <0.7
