name: mycode
version: 0.1
author: Henrik Andersson

ghc-options:
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-unused-top-binds

dependencies:
  - base >=4.12 && <5

default-extensions:
  - OverloadedStrings
  - InstanceSigs
  - StandaloneDeriving

executables:
  ch01:
    source-dirs: ch01
    main: ch01.hs
    other-modules: []
    dependencies:
      - text >=1.2 && <1.3
      - fmt >=0.5 && <0.7
  ch02:
    source-dirs: ch02
    main: Main.hs
    other-modules: Radar
    dependencies:
      - fmt >=0.5 && <0.7
  ch03:
    source-dirs: ch03
    main: Main.hs
    other-modules: []
    dependencies:
      - text >= 1.2 && <1.3
      - bytestring >= 0.10 && <0.11
      - time >= 1.8 && <1.11
      - fmt >=0.5 && <0.7
      - colonnade >= 1.1 && <1.3
      - blaze-html >= 0.9 && <0.10
      - blaze-colonnade >= 1.1 && <1.3
      - Chart >= 1.8 && <1.10
      - Chart-diagrams >= 1.8 && <1.10
      - cassava >= 0.5 && <0.6
      - optparse-applicative >= 0.14 && <0.16

internal-libraries:
  ch02-lib:
    source-dirs: ch02
    exposed-modules: Radar
    other-modules: []
  
tests:
  ch02-tests:
    source-dirs: ch02/tests
    main: Test.hs
    other-modules: []
    dependencies:
      - ch02-lib
      - random >=1.2 && <1.3
